### ISSUE TITLE
HYP3 doesn't download connected components file for unwrapError correction in MIntPY 

### ISSUE THREAD

**Issue by miladmz** [ASFHyP3/hyp3#1174]
HYP3 doesn't download connected components file for unwrapError correction in MIntPY so how can I do this step :
!smallbaselineApp.py confiq.txt --dostep correct_unwrap_error

**Comment by forrestfwilliams** [comment]
Hi @miladmz, unfortunately HyP3 products do not include connected components files at this time. Connected components files are produced by the SNAPHU unwrapping program, which ISCE2 uses, but HyP3 does not use this unwrapper. Because of this I don't believe you can currently perform the `correct_unwrap_error` step with HyP3 data, but you should still be able to perform a reasonable SBAS analysis without performing this step.
