### ISSUE TITLE
Add default project name if none entered (timestamp?) 

### ISSUE THREAD

**Issue by Alex-Lewandowski** [ASFHyP3/hyp3#366]
I created a project of HyP3 jobs in Vertex but forgot to enter a project name. I need to access that batch of jobs and can't add a project name after the fact from Vertex. I'm sure I could figure out how to update the project name from the API or SDK but it was much quicker to just reorder the jobs with the correct project name. If HyP3 added a default project name, I would still have easily been able to access them as a batch.

**Comment by jhkennedy** [comment]
I think I'm going to close this as "won't do". 

Vertex has re-arranged the submission pane so it's a lot harder to forget the job/project names, and since we don't provide any `DELETE` methods, large numbers of project names get rather unweildy. 

Likewise on the SDK side, saving a batch, or just a list of job ids, will let you get back to the project with or without a project name.

I could see revisiting this, if/when we add a DELETE method, or instead providing an UPDATE method so you could add/change a project name.
